Models/ApplicationContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace MyBook.Models;

public class ApplicationContext : IdentityDbContext<User>
{
    public ApplicationContext(DbContextOptions<ApplicationContext> options)
        : base(options)
    {
        Database.EnsureCreated();
    }
}

Models/ErrorViewModel.cs
namespace MyBook.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace MyBook.Models;

public class User : IdentityUser
{
    public int Year { get; set; }
}

ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyBook.ViewModels;

public class LoginViewModel
{
    [Required]
    [Display(Name = "Email")]
    public string Email { get; set; }
         
    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "Пароль")]
    public string Password { get; set; }

    public string? ReturnUrl { get; set; }
}

ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyBook.ViewModels;

public class RegisterViewModel
{
    [Required]
    [Display(Name = "Email")]
    public string Email { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "Пароль")]
    public string Password { get; set; }
 
    // [Required]
    // [Compare("Password", ErrorMessage = "Пароли не совпадают")]
    // [DataType(DataType.Password)]
    // [Display(Name = "Подтвердить пароль")]
    // public string PasswordConfirm { get; set; }
}

Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBook.Models;
using MyBook.ViewModels;

namespace MyBook.Controllers;

public class AccountController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;

    public AccountController(UserManager<User> userManager, SignInManager<User> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }
    [HttpGet]
    public IActionResult Register()
    {
        return Ok();
    }
    [HttpPost]
    public async Task<IActionResult> Register(RegisterViewModel model)
    {
        if(ModelState.IsValid)
        {
            User user = new User { Email = model.Email, UserName = model.Email};
            
            var result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
        }

        return Ok();
    }
    
    // [HttpGet]
    // public IActionResult Index(string returnUrl = null)
    // {
    //     return View(new LoginViewModel { ReturnUrl = returnUrl });
    // }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(LoginViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result =
                await _signInManager.PasswordSignInAsync(model.Email, model.Password, false, false);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Неправильный логин и (или) пароль");
            }
        }

        return Ok();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }
}

Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBook.Controllers;

public class AuthorController : Controller
{
}

Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBook.Controllers;

public class BooksController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Audio()
    {
        return View();
    }

    public IActionResult Free()
    {
        return View();
    }
}

Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBook.Controllers;

public class DashBoardController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyBook.Models;

namespace MyBook.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MyBook.Controllers;

public class LibraryController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/PodcastersController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBook.Controllers;

public class Podcasters : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/SetsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBook.Controllers;

public class Sets : Controller
{
    public IActionResult Novelties()
    {
        return View();
    }
    
    public IActionResult BestBooks()
    {
        return View();
    }
    
    public IActionResult BestAudio()
    {
        return View();
    }
}

Views/Books/Audio.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Audio</h1>
</div>
</body>
</html>

Views/Books/Free.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Free</h1>
</div>
</body>
</html>

Views/Books/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Books</h1>
</div>
</body>
</html>

Views/DashBoard/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>

Views/Home/Index.cshtml
@model MyBook.ViewModels.LoginViewModel;
@{
    ViewData["Title"] = "Mybook";
}

<header>
    <div class="header__container">
        <nav>
            <div class="nav__logo">
                <img src="~/img/logo/logo.svg" alt="">
                <img src="~/img/logo/mybook.svg" alt="">
            </div>
            <div class="nav__search">
                <input type="text" placeholder="Книга или автор">
            </div>
            <div class="nav__links">
                <div><a href="">Что выбрать</a></div>
                <div><a asp-controller="Library" asp-action="Index">Библиотека</a></div>
                <div><a href="">Подписка</a></div>
            </div>
            <div class="nav__btn-login">
                <a href="">Войти</a>
            </div>
        </nav>
        <menu>
            <div>
                <a asp-controller="Books" asp-action="Index" class="menu__link">📖 Книги </a>
            </div>
            <div>
                <a asp-controller="Books" asp-action="Audio" class="menu__link">🎧 Аудиокниги</a>
            </div>
            <div>
                <a href="" class="menu__link">👌 Бесплатные книги</a>
            </div>
            <div>
                <a href="" class="menu__link">🔥 Новинки</a>
            </div>
            <div>
                <a href="" class="menu__link">❤️ Топ книг</a>
            </div>
            <div>
                <a href="" class="menu__link">🎙 Топ аудиокниг</a>
            </div>
            <div>
                <a href="" class="menu__link">🎙 Загрузи свой подкаст</a>
            </div>
        </menu>
    </div>
</header>
<div id="login-layout" class="authorization-layout-none">
    <div class="body__mask"></div>
    <div class="authorization">
        <div class="authorization__container">
            <div class="authorization__title">
                <h1>Вход</h1>
                <button id="login-btn_close">
                    <span>
                        <img src="~/img/close.svg" alt="">
                    </span>
                </button>
            </div>
            <form class="authorization__form" method="post" asp-controller="Account" asp-action="Login">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="authorization__inputs">
                    <div class="authorization__login">
                        <p>Почта или телефон:</p>
                        <input asp-for="Email">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="authorization__password">
                        <p>Пароль:</p>
                        <input asp-for="Password">
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <button type="submit">Войти</button>
            </form>
            <div class="authorization__buttons">
                <button id="transition-register">Зарегистрироваться</button>
            </div>
        </div>
    </div>
</div>
<div id="register-layout" class="authorization-layout-none">
    <div class="authorization">
        <div class="authorization__container">
            <div class="authorization__title">
                <h1>Регистрация</h1>
                <button id="registration-btn_close">
                    <span>
                        <img src="~/img/close.svg" alt="">
                    </span>
                </button>
            </div>
            <form class="authorization__form" asp-controller="Account" asp-action="Register" method="post">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="authorization__inputs">
                    <div class="authorization__login">
                        <p>Ваша электронная почта:</p>
                        <input type="text" asp-for="Email">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="authorization__password">
                        <p>Придумайте пароль, пожалуйста:</p>
                        <input type="password" asp-for="Password">
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <button type="submit">Зарегистрироваться</button>
            </form>
            <div class="authorization__buttons">
                <button id="transition-login">Войти</button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/javascript.js"></script>

Views/Library/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Library</h1>
</div>
</body>
</html>

Views/Podcasters/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Index</h1>
</div>
</body>
</html>

Views/Sets/BestAudio.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Best audio</h1>
</div>
</body>
</html>

Views/Sets/BestBooks.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Best books</h1>
</div>
</body>
</html>

Views/Sets/Novelties.cshtml
<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <h1>Novelties</h1>
</div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="~/css/style.css">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
	<title>MyBook</title>
	<script src="https://code.jquery.com/jquery-3.6.0.js"
		integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</head>
<body>
	@RenderBody()
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>